// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "../interfaces/IZKVerifier.sol";

/// @title PlaceholderVerifier — Temporary ZK Verifier
/// @notice PLACEHOLDER: Always returns true. Replace with auto-generated UltraHonk
///         verifier from Noir circuit compilation before production/mainnet deployment.
/// @dev This exists so the full end-to-end flow (CCIP → ShieldAdapter → HSP) can be
///      tested before the real Noir circuit is compiled into a Solidity verifier.
///      The real verifier will be generated by: nargo compile → bb write_vk → bb contract
contract PlaceholderVerifier is IZKVerifier {
    /// @notice Always returns true — PLACEHOLDER ONLY
    /// @dev In production, this will perform actual pairing checks (UltraHonk/Groth16)
    function verify(bytes calldata /* proof */, bytes32[] calldata /* publicInputs */) external pure override returns (bool) {
        // TODO: Replace with auto-generated verifier from Noir circuit
        // The real verifier will:
        // 1. Deserialize the proof
        // 2. Reconstruct the verification key
        // 3. Perform pairing check (UltraHonk: 4 pairing points)
        // 4. Return true only if the proof is mathematically valid
        return true;
    }
}
